name: Run Test Suite
on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        ruby: [ '3.0',  '3.2', 'jruby-9.4.3.0' ]
    steps:
      - name: Checkout icd-api
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle install --with development

      - name: Run linter
        run: bundle exec rubocop -d --cache true
        if: ${{ matrix.ruby != '2.4' }}

      - name: Run Unit Tests
        run: bundle exec rspec
